{% set version = "0.8.8" %}

package:
  name: ulmo
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/u/ulmo/ulmo-{{ version }}.tar.gz
  sha256: 6ea36b9758d0c397e68d6a37177ba1c7b6b67132cc04c0556fb892ee7e806710

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - appdirs
    - beautifulsoup4
    - future
    - geojson
    - isodate
    - lxml >=4.2.3
    - numpy
    - pandas
    - python
    - requests
    - suds-jurko

test:
  imports:
    - ulmo.usgs.nwis
    - ulmo.cdec.historical
    - ulmo.util
    - ulmo.waterml
    - ulmo.ncdc
    - ulmo.cpc
    - ulmo.cuahsi
    - ulmo.cpc.drought
    - ulmo.ncdc.gsod
    - ulmo.ncdc.cirs
    - ulmo.twc
    - ulmo.cuahsi.his_central
    - ulmo.usgs
    - ulmo.usace.rivergages
    - ulmo
    - ulmo.ncdc.ghcn_daily
    - ulmo.usace.swtwc
    - ulmo.twc.kbdi
    - ulmo.cuahsi.wof
    - ulmo.usace
    - ulmo.cdec
    - ulmo.nasa
    - ulmo.lcra
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ulmo-dev/ulmo
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Clean, simple, and fast access to public hydrology and climatology data
  doc_url: http://ulmo.readthedocs.io/
  dev_url: https://github.com/ulmo-dev/ulmo/

extra:
  recipe-maintainers:
    - emiliom
    - ocefpaf
