{% set version = "0.8.5" %}

package:
  name: ulmo
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/u/ulmo/ulmo-{{ version }}.tar.gz
  sha256: 4725fb0561634169c0ba3cd6a4de055b9f941352d564e5390bd0c189e213e47f

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - appdirs
    - beautifulsoup4
    - future
    - geojson
    - isodate
    - lxml >=4.2.3
    - mock
    - numpy
    - pandas
    - pytables
    - pytest
    - requests
    - suds-jurko
    - freezegun
    - html5lib <=0.9999999

test:
  imports:
    - ulmo.usgs.nwis
    - ulmo.cdec.historical
    - ulmo.util
    - ulmo.waterml
    - ulmo.ncdc
    - ulmo.cpc
    - ulmo.cuahsi
    - ulmo.cpc.drought
    - ulmo.ncdc.gsod
    - ulmo.usgs.eddn
    - ulmo.ncdc.cirs
    - ulmo.twc
    - ulmo.cuahsi.his_central
    - ulmo.usgs
    - ulmo.usace.rivergages
    - ulmo
    - ulmo.ncdc.ghcn_daily
    - ulmo.usace.swtwc
    - ulmo.twc.kbdi
    - ulmo.cuahsi.wof
    - ulmo.usace
    - ulmo.cdec
    - ulmo.nasa
    - ulmo.lcra

about:
  home: https://github.com/ulmo-dev/ulmo
  license: BSD 3-Clause
  summary: 'Clean, simple, and fast access to public hydrology and climatology data'
  doc_url: http://ulmo.readthedocs.io/
  dev_url: https://github.com/ulmo-dev/ulmo/

extra:
  recipe-maintainers:
    - ocefpaf
    - dharhas
