travis:
  secure:
    BINSTAR_TOKEN: ljDd42dxcX2o3TntreY6OhYUkV+MHK7IrvEj+GxxZvldaAn1sFP4bq6zJPOaWYZnCnBTxkBShcEq93yzGDHUSmn0b5AiYkKS6ko+Jb1H+B6r1XXlI3JN+nrnl4g+9NzTdgCcE6XRKaP0tr6YAOjaoYvNDKfna7rI30yqsV99jQ4fCLSN6Edt2SXfZrIkLClWjrHGjnT27WnWV9YBJ9TfnqKSvh+WU/KGIj7iqEIc0S0qAesqDFgUXn6JPQizjWkSTFP+kDRTnnOf0fKJs2GBunUXdAdIe00Slg6zpSe0Bhp2B1MsMPUkLhzZPTJX2IEzxAQYlr65ZNwr5FDk2CqjDsiKcWlmlbG4QwRb6T9iSSEocq7oTpu+G0tuDHmx+mqb1qYLVq13+ntV+F6a1B9Fv7zX4MkXoiQh3hOKcu9lvvdR+C+W342pNqHiYaEk0FNQ+z6Pd9Ams+wR1TjvtjzwMtAGBkSVUS0nbGMw6A8s00D4CmainhMDvgjiMIdL6xbDa30SyFZkT7dx3IzvWXAK3mG3kJeecgrEqKOdH323YphCS/5y1fs+REUCd+FkdVEJ2wUVCuBnTVo7A78qKuCyx3dQTYi8k+ZzMikN8RiLjl2UIJ2pJUD0+5H5dLyyUdpwFRPh2wQsbTkJKBTVOx6laywqa/PFxg1p8TJ4SVIzCyM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
