travis:
  secure:
    BINSTAR_TOKEN: cOt8BIVs0n0dbHPk07tXy5yRV9251R32u/cKO89hJaeAY/bSI9vYQJ+isuAWTwsA1PUZ4dqWIKkurSDYHjimA8g3hID1xjHt7Cax2SR+yscY+0z0rfXlntR4+VBJRcQ2KWPsL3r7jkEpmA7eSW9M1lAkwqC9vViZ5OGrBFBiawCY0mCSrCGTrS+FhWmG382lE9icSqfEpzfrpbAagNlNzfCmEgwNd8idQgRGFoWoZJEWfuR+UI05uReFIFcjdA9tjsgFfZynl/+/hZwlfwlwJ47ekgqM3Rj1txfniIMMG2gKUXHf0TD800/wCYtwyEEl6RujfY2MYGkkv6by/6+bzqaRBHsOFLuelkn6JiNcwb0ENgmBqAffqthXpJdfczDS2YyjqTM8Kk0OUDAPlCobsRTrtlFZysqGfXbpTk2FMoNdCjThrpbo/fQAF1WklkX7kwc5aELtcOVM1ql0m6GcfX8+HrwE2zuoV3/9ikh21udOqXb6A5q/ar9t/BFOd1zPAef3XNKS6rRROrJ4QyfJXnz4kMU16jvzI1fDbludwD+dZAW/4lW5xexdCC/DzpSL8OFFdw9Tfoz1au11+WQU3nS2qr4mup7N42RrU4rmIJ8YuvVeVvvUfbPsSezYmSwoKtmvvvVUa001fKGTtRxXa0/+liIv7rUQUpSqEW6NTXo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
